services:
  api:
    build: .
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8080:8080"
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://localhost/8080/health", "|| exit 1" ]
      interval: 60s
      timeout: 1s
      retries: 15
      start_period: 20s
      start_interval: 1s
    depends_on:
      postgres:
        condition: service_healthy
      liquibase:
        condition: service_completed_successfully
    restart: always

  redis:
    image: redis:8.4
    ports:
      - "6379:6379"
    command: >
      sh -c '
        mkdir -p /usr/local/etc/redis &&
        echo "bind 0.0.0.0" > /usr/local/etc/redis/redis.conf &&
        echo "user default off nopass nocommands" > /usr/local/etc/redis/users.acl &&
        echo "user $REDIS_USER on >$REDIS_PASSWORD allcommands allkeys allchannels" >> /usr/local/etc/redis/users.acl &&
        redis-server /usr/local/etc/redis/redis.conf --aclfile /usr/local/etc/redis/users.acl
      '
    healthcheck:
      test: [ "CMD", "redis-cli", "--user", "$REDIS_USER", "--pass", "$REDIS_PASSWORD", "ping" ]
      interval: 60s
      timeout: 1s
      retries: 15
      start_period: 20s
      start_interval: 1s
    restart: always
  
  postgres:
    image: 'postgres:17.5'
    env_file: .env
    ports:
      - "54320:5432"
    volumes:
      - postgres-storage:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}" ]
      interval: 60s
      timeout: 1s
      retries: 15
      start_period: 20s
      start_interval: 1s
    restart: always

  liquibase:
    image: 'liquibase:4.33'
    env_file: .env
    volumes:
      - ./gymBackendC--.WebApi/Data:/liquibase/changelog
    working_dir: /liquibase/changelog
    depends_on:
      postgres:
        condition: service_healthy
    command: [ "--changeLogFile=changelog.yml", "--url=jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}", "--username=${POSTGRES_USER}", "--password=${POSTGRES_PASSWORD}", "update" ]
    restart: on-failure

volumes:
  redis-storage:
  postgres-storage:
